Resources:
  AtinInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "ec2-key-awslearn" 
      DisableApiTermination: "false" 
      ImageId: "ami-0fbd7e2032a73c4c2"
      InstanceType: "t3.micro"
      Monitoring: "false"
      SecurityGroupIds: 
        - !Ref secGroupName
      Tags:
        - Key: "Name"
          Value: "myfirstInstance"

  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "cfSecGroup"
      GroupDescription: "Created from cloudformation"

      